fn main() {
    #[cfg(windows)]
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "calendar_create_manual",
            "calendar_details",
            "notification_list",
            "notification_parts",
            "retry_part",
            "settings_read",
            "save_source_config",
            "set_model_consent",
            "set_autostart",
            "calendar_query",
            "calendar_edit",
            "calendar_undo",
            "show_vault_window",
            "vault_create",
            "vault_change_master",
            "vault_copy",
            "vault_unlock",
            "vault_list",
            "vault_apply",
            "vault_reveal",
            "vault_lock",
        ]),
    ))
    .expect("desktop configuration invalid");
}
