[package]
name = "shixu-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
log = { version = "=0.4.34", features = ["max_level_info", "release_max_level_info"] }
tungstenite = { version = "=0.30.0", default-features = false, features = ["handshake"] }
shixu-core = { path = "../shixu-core" }
serde.workspace = true
serde_json.workspace = true
zeroize.workspace = true
uuid.workspace = true
sha2 = "=0.11.0"
flate2 = { version = "=1.1.10", default-features = false, features = ["zlib-rs"] }
crc32fast = "=1.5.2"
quick-xml = "=0.42.0"
chrono = { version = "=0.4.45", default-features = false, features = ["std"] }
zip = { version = "=9.0.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }

image = { version = "=0.25.9", default-features = false, features = ["png", "jpeg"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Cryptography", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Threading", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
libloading = "=0.8.9"
serde_json.workspace = true
uuid.workspace = true
rusqlite = { version = "=0.40.2", default-features = false, features = ["bundled"] }
